services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Activity_monitoring_platform_Db

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  station-loader:
    build:
      context: .
      dockerfile: StationLoader/Dockerfile

    depends_on:
      mysql:
        condition: service_healthy

    restart: "no"
